# ~/.config/starship.toml

format = """$python$git_branch$directory\n$character"""

[directory]
style = 'bg:#5986B6 fg:#ffffff'
format = '[ $path ]($style)[](fg:#5986B6)'
truncation_length = 4
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
symbol = ''
style = 'bg:#ffb86c fg:#282a36'
format = '[ $symbol $branch ](fg:#282a36 bg:#ffb86c)[](fg:#ffb86c bg:#5986B6)'

[character]
# Using single quotes to fix the TOML parsing error
success_symbol = '[\[I\]❯](bold green)'
error_symbol = '[\[I\]❯](bold red)'
vicmd_symbol = '[\[N\]❯](bold yellow)'
vimcmd_visual_symbol = '[\[V\]❯](bold blue)'
vimcmd_replace_one_symbol = '[\[R\]❯](bold purple)'
vimcmd_replace_symbol = '[\[R\]❯](bold purple)'

[python]
symbol = " "              # nice Python icon (requires Nerd Font)
style = "bg:#98C379 fg:#282a36"
format = '[ $symbol$virtualenv ]($style)[](fg:#98C379 bg:#ffb86c)'
